### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by BitcoinBrief** [Open-Source-Justice-Foundation/Fundsolvr#64]
### Why Badges?
Badges can be used as rewards to incentivize participation on resolvr and recognize outstanding community members.

Badges could represent achievements to incentivize users to set-up their profile on resolvr.

Badges can also be used to identify resolvr users throughout the nostrverse and possible help filter bounty posts and community polls on resolvr.

### Criteria for Completion
To complete this issue and earn the bounty, 

* create a pull request that implements [Nip-58](https://nostr-nips.com/nip-58) on resolvr.  
* include a badge-type for "Alpha Contributor" (and resolvr will award it to you),
* have PR merged into resolvr.
---
[APPLY FOR BOUNTY](https://resolvr-io.vercel.app/b/naddr1qqdhyetndak8vu3dvfskgem9wvknqvmpvy6rydp3xv6nqcgpz3mhxue69uhhyetvv9ujuerpd46hxtnfdupzqnhexufrllyjg97sfcfhm8ut7vahtjj95z97spya3277zxtlu7wqqvzqqqr4vg4t2fsa)

**Comment by Temidayo32** [comment]
Hi, I am interested in working on this.

**Comment by BitcoinBrief** [comment]
> Hi, I am interested in working on this.

Hi there! Thanks for the interest in Resolvr! The bounty board has gone through a number of revisions since the original bounty was broadcast and posted to resolvr.io.

But nostr badges might still have a place in the current ecosystem roadmap! Please drop into our discord to continue this discussion and we can see where it fits! https://discord.com/invite/DsqRw8My4m
